server {
    listen 5173;
    server_name localhost;

    root /usr/share/nginx/html;
    index index.html;

    # SPA: redireciona todas as rotas para o index.html
    location / {
        try_files $uri $uri/ /index.html;
    }
}